import {
  SiReact, SiTypescript, SiJavascript, SiHtml5, SiCss3, SiTailwindcss,
  SiFramer, SiMui, SiShadcnui, SiNodedotjs, SiExpress, SiMongodb,
  SiJsonwebtokens, SiAxios, SiNodemon, SiGit, SiGithub,
  SiVite, SiVercel, SiPwa, SiSupabase, SiDocker, SiPnpm, SiEslint,
  SiPrettier, SiVitest, SiRedux, SiSass, SiPostcss, SiNextdotjs,
  SiRadixui, SiReactrouter, SiGoogle, SiClaude, SiFigma, SiCanva
} from "react-icons/si";
import { Code } from "lucide-react";

const iconMap = {
  // Frontend
  React: SiReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  HTML5: SiHtml5,
  CSS3: SiCss3,
  "Tailwind CSS": SiTailwindcss,
  "Framer Motion": SiFramer,
  "Material-UI": SiMui,
  "shadcn/ui": SiShadcnui,
  "React Router": SiReactrouter,
  "Next-Themes": SiNextdotjs,
  "Radix UI": SiRadixui,
  "React Player": SiReact,
  "Headless UI": SiReact,
  "React Spring": SiReact,
  Sass: SiSass,
  SCSS: SiSass,
  PostCSS: SiPostcss,
  Autoprefixer: SiPostcss,
  i18next: SiReact,

  // Backend
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  Express: SiExpress,
  MongoDB: SiMongodb,
  Mongoose: SiMongodb,
  JWT: SiJsonwebtokens,
  bcrypt: SiExpress,
  CORS: SiExpress,
  "Cookie Parser": SiExpress,
  Morgan: SiExpress,
  Axios: SiAxios,
  dotenv: SiNodedotjs,
  validator: SiExpress,
  Nodemon: SiNodemon,
  concurrently: SiNodedotjs,

  // Tools
  Git: SiGit,
  GitHub: SiGithub,
  "VS Code": Code,
  Vite: SiVite,
  Vercel: SiVercel,
  "Vercel Blob": SiVercel,
  PWA: SiPwa,
  "HLS.js": SiPwa,
  Zustand: SiReact,
  Supabase: SiSupabase,
  Docker: SiDocker,
  pnpm: SiPnpm,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  Vitest: SiVitest,
  "Redux Toolkit": SiRedux,
  Redux: SiRedux,
  Clerk: SiReact,
  Workbox: SiPwa,
  "Fuse.js": SiJavascript,
  "Dnd-kit": SiReact,
  Figma: SiFigma,
  Canva: SiCanva,

  // AI Tools
  "Google AntiGravity": SiGoogle,
  "Claude Code": SiClaude,
  Claude: SiClaude,
};

export const getTechIcon = (name) => iconMap[name] || Code;

export const techCategories = [
  {
    category: "Frontend",
    items: [
      "React",
      "TypeScript",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "Framer Motion",
      "Material-UI",
      "shadcn/ui",
      "React Router",
      "React Player",
      "Next-Themes",
      "Radix UI",
      "Headless UI",
      "React Spring",
      "Sass",
      "SCSS",
      "PostCSS",
      "Autoprefixer",
      "i18next",
    ],
  },
  {
    category: "Backend",
    items: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "JWT",
      "bcrypt",
      "CORS",
      "Cookie Parser",
      "Morgan",
      "Axios",
      "dotenv",
      "validator",
      "Nodemon",
      "concurrently",
    ],
  },
  {
    category: "Tools",
    items: [
      "Git",
      "GitHub",
      "VS Code",
      "Vite",
      "Vercel",
      "Vercel Blob",
      "PWA",
      "HLS.js",
      "Zustand",
      "Supabase",
      "Docker",
      "pnpm",
      "ESLint",
      "Prettier",
      "Vitest",
      "Redux Toolkit",
      "Clerk",
      "Workbox",
      "Fuse.js",
      "Dnd-kit",
      "Figma",
      "Canva",
    ],
  },
  {
    category: "AI Tools",
    items: ["Google AntiGravity", "Claude Code"],
  },
];